BBG-54: UAA implementation for bets
NovatecConsulting/betting-game-backend pull request #22
Opened 2021-03-25 23:41 UTC by nakhadon

Adds OAuth implementation for adding and retrieving bets.

2021-03-26 12:05 UTC, csh0711 requested changes

2021-03-26 12:05 UTC, csh0711 commented on src/main/kotlin/de/novatec/betting/game/matchdaybet/MatchDayBetRestController.kt
> +    /** Class that handles the mapping of MatchDayBetRequest to MatchDayBet
Hier bitte einen Umbruch vornehmen: 
```
/** 
* Class that handles the mapping of MatchDayBetRequest to MatchDayBet
```

2021-03-26 12:05 UTC, csh0711 commented on src/main/kotlin/de/novatec/betting/game/matchdaybet/MatchDayBetRestController.kt
> +        /** Mapping to MatchDayBet
s.o.

2021-03-26 12:05 UTC, csh0711 reviewed
Bitte noch Postman Prokjet ergänzen
Am besten unter src/test/resources/postman

2021-03-27 15:22 UTC, nakhadon commented
Neue changes hinzugefügt und Postman Import ist unter src/test/resources/postman zu finden!

2021-04-13 20:05 UTC, csh0711 approved these changes

2021-04-13 20:05 UTC, merged